### ISSUE TITLE
AttributeError: 'module' object has no attribute 'JSONDecodeError'

### ISSUE THREAD

**Issue by secufred** [andywalden/esmcheckds2#10]
line 475 of the esmcheckds2.py file I have an error message : AttributeError: 'module' object has no attribute 'JSONDecodeError'

I did replaced the "except json.decoder.JSONDecodeError" by "except ValueError" and it did solved my issue

**Comment by andywalden** [comment]
Thanks for the report! Fix checked into dev for the next release.
