### ISSUE TITLE
Mac and Windows Issues

### ISSUE THREAD

**Issue by WeaveHubHQ** [andywalden/esmcheckds2#13]
Hi Andy,

I tried your new script on both my Mac and Windows computers and ran into the following:

1. The Mac looks like its not doing anything.  When I run the script `python3 esmcheckds2.py -d 0 -f csv`, the script appears to just end and I have a new prompt.

2. On Windows, I get the following error:
`Traceback (most recent call last):
  File "esmcheckds2\console.py", line 278, in <module>
  File "esmcheckds2\console.py", line 205, in main
  File "esmcheckds2\esmcheckds2.py", line 177, in _build_devtree
  File "esmcheckds2\esmcheckds2.py", line 296, in _get_raw_clients
KeyError: 'FTOKEN'
Failed to execute script console`

I definitely have the .mfe-saw.ini in the %APPDATA% and my $HOME directories.
Any thoughts?

**Comment by andywalden** [comment]
Hi, sorry for the delayed response. I'm not sure about the mac, I assumed it would operate much like any *nix environment. I'll need to find a way to test that. 

For the Windows error, I'm pretty sure that's been fixed in the dev branch. I need to get a new release posted but been delayed by the busy season. I'll have something posted soon. Thanks,

**Comment by andywalden** [comment]
Could you please verify if these are fixed in the latest release? 

https://github.com/andywalden/esmcheckds2/releases/latest

**Comment by WeaveHubHQ** [comment]
Hi Andy,

I just gave it a try with the new version and I'm getting a different error:

python3 esmcheckds2 -h 1

  File "esmcheckds2", line 1

SyntaxError: Non-UTF-8 code starting with '\xe8' in file esmcheckds2 on
line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/
for details



Jason S. Lazerus, M.S., GCFA, GPEN, GCIH, GCFE, GCED, GSEC

**Comment by andywalden** [comment]
Thanks. Could you tell me some details about the operating environment and install method please?

**Comment by WeaveHubHQ** [comment]
I'm running this on Mac andI tried through both pip and downloaded the file
from the link you sent me.

I also just tried this on windows and got the following message after
running esmcheckds2.exe -h 1

Traceback (most recent call last):
  File "esmcheckds2\console.py", line 279, in <module>
  File "esmcheckds2\console.py", line 205, in main
  File "esmcheckds2\esmcheckds2.py", line 180, in _build_devtree
  File "esmcheckds2\esmcheckds2.py", line 302, in _get_raw_clients
KeyError: 'FTOKEN'
Failed to execute script console


Jason S. Lazerus, M.S., GCFA, GPEN, GCIH, GCFE, GCED, GSEC

**Comment by andywalden** [comment]
Thanks. Could you tell me the OS versions on the Mac and Windows devices?

**Comment by WeaveHubHQ** [comment]
Mac 10.12.6
Windows 7 x64


Jason S. Lazerus, M.S., GCFA, GPEN, GCIH, GCFE, GCED, GSEC

**Comment by andywalden** [comment]
I posted a new release. I've also determined that ESM 10.0.0, 10.0.0MR1 and 10.0.1 are unsupportable so if you're running one of those please upgrade. Thanks.

https://github.com/andywalden/esmcheckds2/releases/tag/v0.0.7

**Comment by andywalden** [comment]
Assuming fixed for now.
