### ISSUE TITLE
Child Data Sources

### ISSUE THREAD

**Issue by JJ-12134** [andywalden/esmcheckds2#14]
Scripts does not seem to pickup a child Data Source, when I run the script it returns the inactive Data sources, but not the parent or child data sources

**Comment by andywalden** [comment]
Could you confirm which version you're using please? Thanks.

**Comment by JJ-12134** [comment]
HI Andy

Running 10.0.2

**Comment by andywalden** [comment]
Could you please verify if this is fixed in the latest release? 

https://github.com/andywalden/esmcheckds2/releases/latest

**Comment by JJ-12134** [comment]
Hi Andy

Seems to work now, only other issue I have picked up now is that the script
does not exit properly resulting in number of concurrent connections being
reached on ESM

**Comment by andywalden** [comment]
Great, thanks for the feedback. Could you let me know where the the concurrent connection error pops up?

Also, do you have "Active sessions by one user:" set to a non-zero number under System Properties | Login Security?

**Comment by JJ-12134** [comment]
from the application it just states the username or password is incorrect,
if I then try logging in via the gui, i get concurrent sessions reached, we
only allow 2 concurrent user sessions. I did test with my user so will get
another user created.

**Comment by andywalden** [comment]
Fixed in v.0.0.5.
