### ISSUE TITLE
Input Validation Error

### ISSUE THREAD

**Issue by JJ-12134** [andywalden/esmcheckds2#19]
getting "ESM Error: Input Validation Error" on ESM 10.0.1 works fine on ESM 10.0.2

**Comment by andywalden** [comment]
Finally figured this out! In short, the API state for 10.0.0, 10.0.0MR1 and 10.0.1 can be described as "in transition" and not very usable so the fix is to upgrade. It's been a almost a year and 10.2.0 is looking good.
