### ISSUE TITLE
Linux binary 64bit latest release

### ISSUE THREAD

**Issue by Ektoplasma** [andywalden/esmcheckds2#20]
Hello andywalden,

Your tool really works like a charm and I thank you for that. 
However, I am currently using your "Linux binary" version 0.0.4 for some project (can't do otherwise). I wondered if you could upload the Linux binary with the latest version, 0.0.6, or give the procedure (or a link) that could allow me to package it ? The version 0.0.4 works well but I miss the additional options on the latest version !

Thanks.

**Comment by andywalden** [comment]
Sorry about that. I just posted another update including new binaries. 

https://github.com/andywalden/esmcheckds2/releases/tag/v0.0.7
