### ISSUE TITLE
Wiki for functions used in esmcheckds2

### ISSUE THREAD

**Issue by nachiket-lab** [andywalden/esmcheckds2#22]
Hi Andy,

Great job in implementing the esmcheckds2! I was wondering if there is any documentation available for the functions used in the script?
I wanted to write something similar, but could not find any documentation for any of the functions used n the following link:
> https://siemurl/rs/esm/v2/help

Here is an example of what I meant:
`def _get_last_times(self):
        self._method = 'QRY%5FGETDEVICELASTALERTTIME'`

Now, in the above example, how exactly did you identify that the method to be used would be this?

Regards,
NS

**Comment by andywalden** [comment]
Hi - sorry, there is no documentation that I know of. That is the private API. I reverse engineer it and take the risk that it might change as is the case with most private APIs.
