### ISSUE TITLE
Multiple ValueError exceptions for a single try

### ISSUE THREAD

**Issue by indistinctTalk** [andywalden/esmcheckds2#23]
First off, thanks for the tool. 

I think I've found a bug in the handling of different time formats, see the [below block of code from console.py](https://github.com/andywalden/esmcheckds2/blob/master/esmcheckds2/console.py#L49).

```python
    try: 
        time_obj = datetime.strptime(time_str, time_format1)
    except ValueError:
        time_obj = datetime.strptime(time_str, time_format2)
    except ValueError:
        time_obj = datetime.strptime(time_str, time_format3)
    except ValueError:
        logging.debug('Invalid time format: {}'.format(time_str))
        time_obj = None
    return time_obj
```

I don't think the second and third ValueError exceptions will ever get hit. I'm using a time appropriate to `time_format3` and I run up the below error.

```
ValueError: time data '02.11.2018 07:52:37' does not match format '%Y/%m/%d %H:%M:%S'
```

I did some searching around and the appropriate method for nested try/exceptions as per this [ stackoverflow article](https://stackoverflow.com/questions/17322208/multiple-try-codes-in-one-block) would look as follows.

```python
    try:
        time_obj = datetime.strptime(time_str, time_format1)
    except ValueError:
        try:
            time_obj = datetime.strptime(time_str, time_format2)
        except ValueError:
            try:
                time_obj = datetime.strptime(time_str, time_format3)
            except ValueError:
                logging.debug('Invalid time format: {}'.format(time_str))
                time_obj = None
    return time_obj
```

I think that'll probably sort it but it's also a little ugly. A valid alternative might be splitting it out into a function as per [this article](https://stackoverflow.com/questions/1322464/python-time-format-check). Do you have any preference? 

Only one other small thing to note is a documentation fix, line 36 of the same file references `DD/MM/YYYY HH:MM:SS` when it should be `DD.MM.YYYY HH:MM:SS`.

**Comment by andywalden** [comment]
Thanks. Good call. My logic would only have worked had they been different Exceptions. Replaced with a library anyway. No reason to be reinventing wheels.
