### ISSUE TITLE
API Help

### ISSUE THREAD

**Issue by bearjew91** [andywalden/esmcheckds2#25]
Hi Andy,

I am working on my own API project that's how i got here, i was wondering if you could help me writing a query for a specific data source, i managed to get events but i just cant find the right filter to filter by data sources, any help much appreciated!  I have attached the filter fileds i got from the esm. Thanks in advance, Adam
[filter_fields.txt](https://github.com/andywalden/esmcheckds2/files/3454226/filter_fields.txt)

**Comment by andywalden** [comment]
Hi Adam,

Use 'devGetDeviceList' to get a list of devices and their IPSID, then use that as a filter in your query. 

Here is a working query:

    {'config': 
      {'timeRange': 'PREVIOUS_DAY', 
       'fields': [{'name': 'FirstTime'}, {'name': 'EventCount'}, {'name': 'DSIDSigID'}, {'name': 'IPSIDAlertID'}, {'name': 'AlertID'}, {'name': 'IPSID'}, {'name': 'SigID'}, {'name': 'SrcIP'}, {'name': 'DstIP'}, {'name': 'DomainID'}, {'name': 'Sensor_Name'}, {'name': 'ThirdPartyType.Name'}], 
        'filters': 
            [{'type': 'EsmFieldFilter', 
            'field': {'name': 'SrcIP'}, 
            'operator': 'EQUALS', 
            'values': [{'type': 'EsmBasicValue', 'value': '10.10.22.50'}]}, 
            {'type': 'EsmFieldFilter', 
             'field': {'name': 'IPSID'}, 
             'operator': 'EQUALS', 
             'values': [{'type': 'EsmBasicValue', 'value': '144116287604260864'}]}], 
        'order': [{'direction': 'ASCENDING', 
        'field': {'name': 'FirstTime'}}], 
        'includeTotal': False, 
        'limit': 5000}}

**Comment by bearjew91** [comment]
ooohh thanks a lot dude i used 'in' instead of equals it made the
difference thanks a lot again man!!!!

**Comment by bearjew91** [comment]
Hey,

I am  trying to get child datasources,  i found this related to the issue
but doen not seem to be returning the needed information...
https://community.mcafee.com/t5/Security-Information-and-Event/Enumerating-Client-Datasources-through-ESM-API/m-p/624882
thanks again for all the help!

Adam

**Comment by bearjew91** [comment]
what i meant is client devices to be accurate...

**Comment by andywalden** [comment]
Hi Adam,

There are some new methods for clients in 11.2 (released yesterday), but for a quick fix, you could do the following to get a list of clients.

![clients](https://user-images.githubusercontent.com/16884885/62406170-38304780-b575-11e9-8116-211242d09d6e.png)

**Comment by bearjew91** [comment]
Hey, thanks for reaching out, i have just wrote a simular one woth adding
256 to the parrent id, seems to be working fine actually, i just need to do
some testing to see what happens if there are several groups under the
parrent.

Have a great weekend!

Adam

**Comment by bearjew91** [comment]
Thought i would share it with you een tho most likely you will not need it
but still :)

method = 'grpGetDeviceTree?hideDisabledDevices=false'
url = base_url+method
resp = requests.post(url, headers=headers, verify=False)
devices = json.loads(resp.text)
print(resp.text)
for device in devices:
    print((devices[0])['name'])
    esm_devices = device['children']
    for esm_device in esm_devices:
        print('\t'+esm_device['name'])
        datasources = esm_device['children']
        for datasource in datasources:
            print('\t\t'+datasource['name'])
            datasource_id = datasource['id']
            datasource_clients = datasource['children']
            if len(datasource_clients) is not 0:
                parent_id = int(datasource_id)
                client_method = 'dsGetDataSourceDetail'
                client_url = base_url+client_method
                while True:
                    try:
                        parent_id = parent_id +256
                        client_params = {"datasourceId": str(parent_id)}
                        client_data = json.dumps(client_params)
                        client_resp = requests.post(client_url,
headers=headers, data=client_data, verify=False)
                        client_resp_data = json.loads(client_resp.text)
                        print('\t\t\t'+client_resp_data['name'])
                    except:
                        break




[image: image.png]

**Comment by bearjew91** [comment]
Hey Andy,

I was wondering if you knew any other way to export correlation rules other
than from the GUI and preferably with the API or SSH

Thank You,

Adam

**Comment by andywalden** [comment]
Perhaps. Could you help me understand the use case? Are you exporting custom rules or making a backup or something else? Thanks.

> Hey Andy, I was wondering if you knew any other way to export correlation rules other than from the GUI and preferably with the API or SSH Thank You, Adam

**Comment by bearjew91** [comment]
Hey,

Yes, my first goal is create backup files for everything, correlations,
policies, watchlists, alarms. The second reason is i am working on a tool
that can help me understand how a correlation was built and have all his
details without opening them in the ESM, right now i am writing a parser
that gathers all the fileds from the xml file but in the end i would like
it as a task that can run automaticly and also monitor for changes, some
customers we share with my colleuges and even tho we do make notes on every
breath we take at work, we are still humans making human mistakes...

**Comment by andywalden** [comment]
Is it possible to accomplish your goal manually in the UI? If so, could you list the steps?

Any reason not to use the backup functionality built into the product? Thanks.

**Comment by bearjew91** [comment]
Does the esm configuration backup include all that? We always create
seperate backups? It can be done in the ui but i want to do it as daily
task instead of doin it manually...

**Comment by bearjew91** [comment]
Hey Andy,

I wrote a little js to open tabs in the esm and also loop them, very
usefull when somebody has only one screen but multiple dashboards, also it
doen not need installation and work with all browser as far as i know, if
you want it i would like to share it with you, maybe i can give sonething
back for all the help you gave 😊

Adam

**Comment by andywalden** [comment]
Check out System Properties | ESM Management | Settings Backup. You will see that you can schedule the backup and point the file to a remote share. Does this work for your goal? Thanks.

![setting_backup](https://user-images.githubusercontent.com/16884885/63307337-15639a00-c2bc-11e9-987b-a63003909f65.PNG)

**Comment by andywalden** [comment]
Sounds interesting. I would like to check it out. Thanks.

>

**Comment by bearjew91** [comment]
Hey,

For the backup it should be fine even tho i would like to have the files
separated, but i also need to add it to my script that pulls the
correlations by it self and converts it to readable format in excel,
Lately i read the document of 10.4 and it says McAfee is removing a bunch
of API commands for security reasons?! That can not be true...:(

**Comment by andywalden** [comment]
![api](https://user-images.githubusercontent.com/16884885/67537286-b1d55e80-f6a8-11e9-8520-f4ee3f301ba0.jpg)

They brought back the critical methods in 11.2.1, patch 4 (inquire with support, it's up to patch 7 now).
