### ISSUE TITLE
Required permissions

### ISSUE THREAD

**Issue by indistinctTalk** [andywalden/esmcheckds2#27]
The README states that `ESM Credentials and proper permissions` are required, without stating what those proper permissions are. Looking at the code, there's the line `The "Administrator Rights" box must be checked for the user`. 

Requiring full administrator access seems like overkill, is it really necessary?

**Comment by andywalden** [comment]
I have updated the readme. There button at the bottom of System Properties labeled "View Reports" where the data source last times are scraped from. Any account that can see this button is able to run this script. If you're able to find a set of permissions that allow this button to appear with less that admin privileges please let me know. Thanks.

![view_reports](https://user-images.githubusercontent.com/16884885/63692578-ff843680-c7df-11e9-8254-62cf4e19685e.png)

**Comment by indistinctTalk** [comment]
Ah okay, thanks. I'll play around a little and update if I find anything.
